import { QuestionDifficulty } from "../lib/types";

/**
 * Hand-written (by Claude, directly in conversation — not via an API call)
 * starter question bank: 5 questions per category across all 57 entries in
 * `categoryTaxonomy.ts`. This is what `seedPregeneratedQuestions.ts` loads
 * and uploads — no `ANTHROPIC_API_KEY` needed for this path at all, since
 * the writing already happened, once, right here.
 *
 * This is a STARTER pool, not the final word — `seedCategoryTaxonomy.ts`
 * (which does call the Claude API) can top any of these categories up with
 * more later once you have your own key, and so can the in-app "Generate
 * with AI" button on a home-turf category.
 *
 * Keys must match `CategorySeed.id` values in `categoryTaxonomy.ts` exactly.
 */
export interface PregeneratedQuestion {
  questionText: string;
  options: [string, string, string, string];
  correctAnswerIndex: number;
  difficulty: QuestionDifficulty;
}

export const PREGENERATED_QUESTIONS: Record<string, PregeneratedQuestion[]> = {
  "sports-general": [
    { questionText: "كم لاعبًا أساسيًا يشارك من فريق كرة السلة داخل الملعب في آن واحد؟", options: ["4", "5", "6", "7"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "في أي عام أقيمت أول دورة ألعاب أولمبية حديثة؟", options: ["1896", "1900", "1904", "1912"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم عدد الأشواط الأساسية في مباراة كرة السلة الاحترافية (NBA)؟", options: ["2", "3", "4", "5"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "أي دولة استضافت كأس العالم لكرة القدم عام 2022؟", options: ["قطر", "البرازيل", "روسيا", "ألمانيا"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي المسافة الرسمية لسباق الماراثون؟", options: ["42.195 كم", "40 كم", "50 كم", "35 كم"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "football-general": [
    { questionText: "كم عدد اللاعبين الأساسيين لفريق كرة القدم داخل الملعب؟", options: ["9", "10", "11", "12"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "كم دقيقة يستغرق الشوط الواحد في مباراة كرة القدم؟", options: ["30", "40", "45", "50"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "من هو اللاعب الحائز على أكبر عدد من جوائز الكرة الذهبية؟", options: ["ليونيل ميسي", "كريستيانو رونالدو", "بيليه", "مارادونا"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي دولة فازت بأكبر عدد من بطولات كأس العالم لكرة القدم؟", options: ["البرازيل", "ألمانيا", "إيطاليا", "الأرجنتين"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم البطاقة التي يُطرد بها اللاعب من المباراة؟", options: ["الصفراء", "الحمراء", "الخضراء", "الزرقاء"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "real-madrid": [
    { questionText: "في أي مدينة يقع مقر نادي ريال مدريد؟", options: ["مدريد", "برشلونة", "إشبيلية", "بلباو"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الملعب الرئيسي لنادي ريال مدريد؟", options: ["سانتياغو برنابيو", "كامب نو", "واندا متروبوليتانو", "سان مامس"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الهداف التاريخي لنادي ريال مدريد؟", options: ["كريستيانو رونالدو", "راؤول غونزاليس", "ألفريدو دي ستيفانو", "كريم بنزيمة"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم مرة توّج ريال مدريد بلقب دوري أبطال أوروبا حتى نهاية موسم 2024؟", options: ["12 مرة", "13 مرة", "14 مرة", "15 مرة"], correctAnswerIndex: 3, difficulty: "hard" },
    { questionText: "من هو المدرب الذي قاد ريال مدريد للفوز بثلاثة ألقاب متتالية في دوري أبطال أوروبا (2016-2018)؟", options: ["زين الدين زيدان", "كارلو أنشيلوتي", "جوزيه مورينيو", "بيب غوارديولا"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "barcelona": [
    { questionText: "في أي مدينة يقع مقر نادي برشلونة؟", options: ["برشلونة", "مدريد", "بلباو", "فالنسيا"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم ملعب نادي برشلونة؟", options: ["كامب نو", "سانتياغو برنابيو", "رامون سانشيز بيثخوان", "مستايا"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو اللاعب الأكثر تسجيلاً للأهداف في تاريخ نادي برشلونة؟", options: ["ليونيل ميسي", "رونالدينيو", "نيمار", "تشافي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الشعار المرتبط تقليديًا بنادي برشلونة؟", options: ["أكثر من مجرد نادٍ", "النادي الملكي", "الفريق الأحمر", "قلعة الأبطال"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "في أي عام تأسس نادي برشلونة؟", options: ["1899", "1902", "1905", "1910"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "man-utd": [
    { questionText: "في أي مدينة إنكليزية يقع نادي مانشستر يونايتد؟", options: ["مانشستر", "ليفربول", "لندن", "ليدز"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم ملعب نادي مانشستر يونايتد؟", options: ["أولد ترافورد", "أنفيلد", "الإمارات", "ستامفورد بريدج"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو المدرب الذي قاد مانشستر يونايتد لأطول فترة تدريبية ناجحة بين 1986 و2013؟", options: ["أليكس فيرغسون", "جوزيه مورينيو", "لويس فان غال", "إريك تين هاغ"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الهداف التاريخي لنادي مانشستر يونايتد؟", options: ["واين روني", "بوبي تشارلتون", "رايان غيغز", "دينيس لو"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "في أي موسم حقق مانشستر يونايتد الثلاثية التاريخية (الدوري والكأس ودوري الأبطال)؟", options: ["1998-1999", "2007-2008", "1993-1994", "2012-2013"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "liverpool": [
    { questionText: "ما اسم ملعب نادي ليفربول؟", options: ["أنفيلد", "أولد ترافورد", "غوديسون بارك", "الاتحاد"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو النشيد الشهير المرتبط بجماهير ليفربول؟", options: ["You'll Never Walk Alone", "We Are the Champions", "Glory Glory", "One Love"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم مرة فاز ليفربول بلقب دوري أبطال أوروبا حتى عام 2019؟", options: ["4 مرات", "5 مرات", "6 مرات", "7 مرات"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "من هو المدرب الذي قاد ليفربول للفوز بلقب دوري أبطال أوروبا عام 2019؟", options: ["يورغن كلوب", "رافائيل بينيتيز", "بريندان رودجرز", "كيني دالغليش"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "بأي لون يرتدي فريق ليفربول قميصه الأساسي؟", options: ["الأحمر", "الأزرق", "الأبيض", "الأسود"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "arab-national-teams": [
    { questionText: "أي منتخب عربي كان أول من تأهل لكأس العالم لكرة القدم؟", options: ["مصر", "المغرب", "السعودية", "الجزائر"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي منتخب عربي وصل إلى ربع نهائي كأس العالم 2022؟", options: ["المغرب", "تونس", "السعودية", "قطر"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "كم مرة فاز المنتخب المصري بكأس الأمم الأفريقية (رقم قياسي)؟", options: ["5 مرات", "6 مرات", "7 مرات", "8 مرات"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "أي دولة عربية استضافت كأس العالم لكرة القدم عام 2022؟", options: ["قطر", "الإمارات", "السعودية", "الكويت"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي منتخب عربي يُلقب بـ\"أسود الأطلس\"؟", options: ["المغرب", "الجزائر", "تونس", "ليبيا"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "world-cup": [
    { questionText: "أي دولة فازت بأول نسخة من كأس العالم لكرة القدم عام 1930؟", options: ["أوروغواي", "الأرجنتين", "البرازيل", "إيطاليا"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كل كم سنة يُقام كأس العالم لكرة القدم؟", options: ["سنتين", "3 سنوات", "4 سنوات", "5 سنوات"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "أي منتخب فاز بكأس العالم 2022 في قطر؟", options: ["الأرجنتين", "فرنسا", "البرازيل", "كرواتيا"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو اللاعب الذي سجل هاتريك في نهائي كأس العالم 2022؟", options: ["كيليان مبابي", "ليونيل ميسي", "أنخيل دي ماريا", "أوليفييه جيرو"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي دولة فازت بأكبر عدد من كؤوس العالم حتى الآن؟", options: ["البرازيل", "ألمانيا", "إيطاليا", "الأرجنتين"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "basketball-nba": [
    { questionText: "كم عدد اللاعبين الأساسيين لفريق كرة السلة داخل الملعب؟", options: ["4", "5", "6", "7"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "من هو لاعب كرة السلة الملقب بـ\"الملك\" (King James)؟", options: ["ليبرون جيمس", "مايكل جوردان", "كوبي براينت", "كيفن دورانت"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "مع أي فريق قضى مايكل جوردان معظم مسيرته الاحترافية؟", options: ["شيكاغو بولز", "لوس أنجلوس ليكرز", "بوسطن سلتيكس", "ميامي هيت"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "كم عدد أشواط مباراة NBA ومدة كل شوط؟", options: ["4 أشواط × 12 دقيقة", "شوطان × 20 دقيقة", "4 أشواط × 10 دقائق", "3 أشواط × 15 دقيقة"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو صاحب الرقم القياسي لأكثر نقاط في تاريخ NBA؟", options: ["ليبرون جيمس", "كريم عبد الجبار", "مايكل جوردان", "كوبي براينت"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "tennis": [
    { questionText: "بكم شوطًا يفوز اللاعب عادة في مباراة غراند سلام للرجال؟", options: ["شوطين من 3", "3 أشواط من 5", "شوط واحد فقط", "4 أشواط من 7"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "ما هي البطولات الأربع الكبرى (غراند سلام) في التنس؟", options: ["أستراليا ورولان غاروس وويمبلدون وأميركا المفتوحة", "ويمبلدون فقط", "بطولة عالمية واحدة", "الألعاب الأولمبية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو صاحب أكبر عدد من ألقاب الغراند سلام بين الرجال حتى 2023؟", options: ["نوفاك ديوكوفيتش", "رافائيل نادال", "روجيه فيدرر", "أندي موراي"], correctAnswerIndex: 0, difficulty: "hard" },
    { questionText: "على أي سطح تُقام بطولة ويمبلدون؟", options: ["العشب", "الطين (التراب الأحمر)", "الأسفلت الصلب", "الرمل"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "كم عدد النقاط المطلوبة للفوز بشوط (Game) واحد في التنس بدون تعادل؟", options: ["3 نقاط", "4 نقاط", "5 نقاط", "6 نقاط"], correctAnswerIndex: 1, difficulty: "medium" },
  ],
  "movies-general": [
    { questionText: "من هو المخرج المعروف بأفلام \"إنسبشن\" و\"إنترستيلر\"؟", options: ["كريستوفر نولان", "ستيفن سبيلبرغ", "جيمس كاميرون", "مارتن سكورسيزي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي فيلم يُعد من أعلى الأفلام إيرادات في تاريخ السينما؟", options: ["أفاتار", "أفنجرز: نهاية اللعبة", "تايتانيك", "ستار وورز"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي أشهر جائزة سنوية للأفلام في هوليوود؟", options: ["الأوسكار", "الغولدن غلوب", "الغرامي", "الإيمي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من أخرج فيلم \"تايتانيك\" عام 1997؟", options: ["جيمس كاميرون", "ستيفن سبيلبرغ", "رون هاورد", "ريدلي سكوت"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو أول فيلم رسوم متحركة طويل أنتجته والت ديزني؟", options: ["سنو وايت والأقزام السبعة", "سندريلا", "بينوكيو", "الأسد الملك"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "marvel": [
    { questionText: "من هو المؤسس الأشهر لشركة مارفل كوميكس؟", options: ["ستان لي", "والت ديزني", "جاك كيربي", "بوب كين"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم البطل الخارق المليونير الذي يرتدي درعًا معدنيًا؟", options: ["آيرون مان", "باتمان", "كابتن أميركا", "ثور"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الشرير الرئيسي في فيلم \"أفنجرز: إنفينيتي وور\"؟", options: ["ثانوس", "لوكي", "ألترون", "رِد سكال"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "كم عدد أحجار اللانهاية (Infinity Stones) في عالم مارفل السينمائي؟", options: ["4", "5", "6", "7"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "من هو الممثل الذي جسّد شخصية آيرون مان؟", options: ["روبرت داوني جونيور", "كريس إيفانز", "كريس هيمسوورث", "مارك روفالو"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "harry-potter": [
    { questionText: "في أي مدرسة يدرس هاري بوتر السحر؟", options: ["هوغوورتس", "دورمشتانغ", "بوباتون", "إلفينستون"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هما أفضل صديقين لهاري بوتر؟", options: ["رون ويزلي وهيرميون غرينجر", "درايكو مالفوي ولونا", "نيفيل وسيدريك", "فريد وجورج"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الساحر الشرير الرئيسي في سلسلة هاري بوتر؟", options: ["فولدمورت", "سيفيروس سناب", "لوسيوس مالفوي", "بيلاتريكس"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "إلى أي بيت ينتمي هاري بوتر في هوغوورتس؟", options: ["غريفندور", "سليذرين", "هافلباف", "رافنكلو"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هي مؤلفة سلسلة روايات هاري بوتر؟", options: ["ج.ك. رولينغ", "ستيفن كينغ", "ج.ر.ر. تولكين", "سوزان كولينز"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "star-wars": [
    { questionText: "من هو الأب الحقيقي لشخصية لوك سكايووكر؟", options: ["دارث فيدر", "أوبي وان كينوبي", "يودا", "هان سولو"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم السفينة الفضائية الشهيرة التي يقودها هان سولو؟", options: ["الصقر الألفي", "نجمة الموت", "إكسكاليبر", "إنتربرايز"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من أخرج الفيلم الأول من سلسلة حرب النجوم عام 1977؟", options: ["جورج لوكاس", "ستيفن سبيلبرغ", "جيمس كاميرون", "ريدلي سكوت"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما اسم المحارب الذي يرتدي قناعًا أسود ويتنفس بصوت مميز؟", options: ["دارث فيدر", "ستورم تروبر", "جابا الهت", "بوبا فيت"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم الكائنات الصغيرة ذات الفراء البني التي ظهرت في \"عودة الجيداي\"؟", options: ["الإيووك", "الجاوا", "الووكي", "الدرويد"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "tv-shows-general": [
    { questionText: "أي مسلسل يدور حول معلم كيمياء يتحول إلى تاجر مخدرات؟", options: ["Breaking Bad", "The Office", "Friends", "Lost"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي مسلسل كوميدي يدور حول مجموعة أصدقاء في نيويورك وعُرض من 1994 إلى 2004؟", options: ["Friends", "Seinfeld", "The Big Bang Theory", "How I Met Your Mother"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي شبكة بث أنتجت مسلسل \"صراع العروش\"؟", options: ["HBO", "Netflix", "ABC", "NBC"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما اسم المسلسل الذي يتناول قصة عائلة في عالم الجريمة المنظمة بإدارة توني سوبرانو؟", options: ["The Sopranos", "The Wire", "Narcos", "Fargo"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي مسلسل تدور أحداثه في مستشفى \"سياتل غريس\"؟", options: ["Grey's Anatomy", "ER", "House", "Scrubs"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "friends": [
    { questionText: "ما هي مهنة \"روس غيلر\" في مسلسل Friends؟", options: ["عالم حفريات (باليونتولوجي)", "طبيب", "محامٍ", "طباخ"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هي الشخصية التي تعمل طباخة وتفتح مطعمها الخاص لاحقًا؟", options: ["مونيكا غيلر", "ريتشل غرين", "فيبي بوفيه", "جوي تريبياني"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو المقهى الذي يجتمع فيه الأصدقاء باستمرار؟", options: ["Central Perk", "Starbucks", "The Coffee Bean", "Joey's"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هي الممثلة التي جسّدت شخصية \"ريتشل غرين\"؟", options: ["جينيفر أنيستون", "كورتني كوكس", "ليزا كودرو", "أليسون هانيغان"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم قرد \"روس\" الأليف في أحد مواسم المسلسل؟", options: ["ماركل", "تشاندلر", "جيرالدو", "فيبي"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "got": [
    { questionText: "في أي قارة خيالية تدور معظم أحداث \"صراع العروش\"؟", options: ["ويستروس", "ميروين", "إيسوس", "نارنيا"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "إلى أي عائلة ينتمي جون سنو في بداية الأحداث؟", options: ["ستارك", "لانيستر", "تارغيريان", "باراثيون"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هي الشخصية الملقبة بـ\"أم التنانين\"؟", options: ["دينيريس تارغيريان", "سيرسي لانيستر", "سانسا ستارك", "برين تارث"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو العرش الذي يتصارع عليه الجميع في المسلسل؟", options: ["العرش الحديدي", "عرش الأسد", "عرش التنين", "عرش الشتاء"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "عن أي سلسلة روايات اقتُبس مسلسل صراع العروش؟", options: ["أغنية الجليد والنار", "سيد الخواتم", "الحلقات الأولى", "الرحالة"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "anime-general": [
    { questionText: "ما هو أصل مصطلح \"أنمي\"؟", options: ["رسوم متحركة يابانية", "أفلام كرتونية أمريكية", "ألعاب فيديو يابانية", "روايات مصورة"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم الرسوم المصورة اليابانية التي يُقتبس منها الأنمي غالبًا؟", options: ["مانغا", "كوميكس", "غرافيك نوفيل", "أنمي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي استوديو ياباني اشتهر بأفلام \"رحلة تشيهيرو\" و\"قلعة هاول المتحركة\"؟", options: ["استوديو جيبلي", "تويي أنيميشن", "مادهاوس", "سنليونك"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو المخرج الشهير المؤسس لاستوديو جيبلي؟", options: ["هاياو ميازاكي", "أوسامو تيزوكا", "ماكوتو شينكاي", "أكيرا تورياما"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما اسم الأنمي الذي يدور حول صبي يحلم بأن يصبح \"ملك القراصنة\"؟", options: ["ون بيس", "ناروتو", "دراغون بول", "بليتش"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "one-piece": [
    { questionText: "ما اسم بطل أنمي ون بيس الذي يحلم بأن يصبح \"ملك القراصنة\"؟", options: ["مونكي دي لوفي", "زورو", "سانجي", "نامي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي القدرة التي اكتسبها لوفي بعد تناوله فاكهة الشيطان؟", options: ["جسده يتمدد كالمطاط", "التحكم بالنار", "الطيران", "التحول لحيوان"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم سفينة طاقم قبعة القش الرئيسية؟", options: ["ساوزاند صنّي", "الصقر الألفي", "تيتانيك", "كوين آن"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو الكنز الأسطوري الذي يبحث عنه جميع القراصنة في المسلسل؟", options: ["ون بيس", "الجوهرة الزرقاء", "تاج البحر", "كنز الملوك"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو مؤلف ورسام مانغا ون بيس؟", options: ["إيتشيرو أودا", "أكيرا تورياما", "ماساشي كيشيموتو", "تسوغومي أوبا"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "naruto": [
    { questionText: "ما اسم القرية التي ينتمي إليها ناروتو أوزوماكي؟", options: ["قرية الورق (كونوها)", "قرية الرمل", "قرية الضباب", "قرية الصخر"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الكائن المختوم داخل جسد ناروتو منذ ولادته؟", options: ["الثعلب ذو التسعة أذيال", "تنين", "عنقاء", "أفعى عملاقة"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو أفضل صديق ومنافس ناروتو المنتمي لعشيرة الأوتشيها؟", options: ["ساسكي أوتشيها", "كاكاشي", "شيكامارو", "إيتاتشي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم تقنية ناروتو الشهيرة التي يُكوّن بها كرة طاقة في يده؟", options: ["راسينغان", "تشيدوري", "كاماهاماها", "رينيغان"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو معلم فريق ناروتو السابع؟", options: ["كاكاشي هاتاكي", "إيروكا", "جيرايا", "تسونادي"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "arabic-drama-general": [
    { questionText: "أي دولة عربية اشتهرت تاريخيًا بلقب \"هوليوود الشرق\" في صناعة الدراما والسينما؟", options: ["مصر", "لبنان", "سوريا", "المغرب"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "في أي شهر يُعرض تقليديًا أكبر موسم للمسلسلات العربية؟", options: ["رمضان", "الصيف", "الشتاء", "بداية السنة"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الاسم الشائع لمسلسلات الحلقة اليومية التي تُعرض في رمضان؟", options: ["المسلسلات الرمضانية", "السهرات", "البرامج الحوارية", "الأفلام الوثائقية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "بأي فن اشتهر الفنان المصري عادل إمام بشكل أساسي؟", options: ["الكوميديا", "التراجيديا", "الغناء", "الرقص"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي دولة عربية تُعد من أكبر منتجي الدراما التلفزيونية إلى جانب مصر؟", options: ["سوريا", "ليبيا", "اليمن", "السودان"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "classic-egyptian-films": [
    { questionText: "من هو الفنان المصري الملقب بـ\"عبقري الكوميديا\" في الأفلام الكلاسيكية؟", options: ["إسماعيل ياسين", "فريد شوقي", "عمر الشريف", "رشدي أباظة"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هي الفنانة المصرية الملقبة بـ\"سيدة الشاشة العربية\"؟", options: ["فاتن حمامة", "سعاد حسني", "ماجدة", "شادية"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو الممثل المصري الذي مثّل في فيلم \"لورنس العرب\" العالمي؟", options: ["عمر الشريف", "أحمد زكي", "نور الشريف", "محمود ياسين"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو المخرج المصري الذي أخرج فيلم \"المومياء\" عام 1969؟", options: ["شادي عبد السلام", "يوسف شاهين", "صلاح أبو سيف", "هنري بركات"], correctAnswerIndex: 0, difficulty: "hard" },
    { questionText: "أي فنانة مصرية لُقبت بـ\"سندريلا الشاشة العربية\"؟", options: ["سعاد حسني", "فاتن حمامة", "نادية لطفي", "ليلى مراد"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "ramadan-series": [
    { questionText: "متى تبدأ المسلسلات الرمضانية عادةً بالعرض؟", options: ["اليوم الأول من رمضان", "منتصف رمضان", "قبل رمضان بشهر", "بعد عيد الفطر"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي دولة عربية تُعد من أكبر منتجي المسلسلات الرمضانية إلى جانب مصر؟", options: ["سوريا", "تونس", "ليبيا", "اليمن"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم عدد الحلقات المعتاد لمسلسل رمضاني بمعدل حلقة يوميًا؟", options: ["حوالي 30 حلقة", "10 حلقات", "60 حلقة", "5 حلقات"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي نوع من البرامج يُعرض عادة بعد الإفطار مباشرة في رمضان إلى جانب المسلسلات؟", options: ["برامج المقالب والفوازير", "الأفلام الأجنبية", "المباريات الرياضية", "نشرات الطقس"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الطابع الغالب على معظم المسلسلات الرمضانية العربية؟", options: ["الدراما الاجتماعية والعائلية", "الخيال العلمي", "الرعب", "الأنمي"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "arabic-comedy": [
    { questionText: "من هو الفنان المصري الملقب بـ\"الزعيم\" في السينما الكوميدية؟", options: ["عادل إمام", "محمد هنيدي", "أحمد حلمي", "كريم عبد العزيز"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الفنان السوري الشهير بأداء شخصية \"غوار الطوشة\"؟", options: ["دريد لحام", "ياسر العظمة", "نهاد قلعي", "أيمن زيدان"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي فنان مصري اشتهر بأفلام كوميدية شبابية مثل \"صعيدي في الجامعة الأمريكية\"؟", options: ["محمد هنيدي", "أحمد حلمي", "كريم عبد العزيز", "عمرو سعد"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو بطل فيلم \"اللمبي\" الكوميدي المصري؟", options: ["محمد سعد", "أحمد حلمي", "هاني رمزي", "أحمد آدم"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أين تدور أحداث مسرحية \"مدرسة المشاغبين\" المصرية الشهيرة؟", options: ["مدرسة", "مستشفى", "سجن", "الجيش"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "turkish-dubbed-drama": [
    { questionText: "ما هي اللغة الأصلية للمسلسلات التركية التي تُعرض مدبلجة للعربية؟", options: ["التركية", "الفارسية", "الكردية", "الأذرية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي لهجة عربية استُخدمت غالبًا في دبلجة أوائل المسلسلات التركية الشهيرة؟", options: ["اللهجة السورية", "اللهجة المصرية", "اللهجة الخليجية", "الفصحى فقط"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي مسلسل تركي يُعتبر من أوائل من حقق شهرة واسعة في العالم العربي حول عام 2008؟", options: ["سنوات الضياع (نور)", "وادي الذئاب", "حريم السلطان", "قيامة أرطغرل"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي مسلسل تركي تاريخي يتناول قيام الدولة العثمانية ولاقى رواجًا كبيرًا عربيًا؟", options: ["قيامة أرطغرل", "حريم السلطان", "وادي الذئاب", "العشق الممنوع"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "بماذا يتعلق مسلسل \"حريم السلطان\" التركي؟", options: ["حياة البلاط العثماني في عهد سليمان القانوني", "الحرب العالمية الأولى", "الثورة الفرنسية", "تاريخ مصر القديم"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "music-general": [
    { questionText: "كم عدد الأوتار في الغيتار الكلاسيكي القياسي؟", options: ["4", "5", "6", "7"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "من هو الملحن الألماني الشهير الذي فقد سمعه واستمر بالتلحين؟", options: ["بيتهوفن", "موتسارت", "باخ", "شوبان"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي الآلة الوترية التي تُعتبر رمزًا للموسيقى العربية الكلاسيكية؟", options: ["العود", "الغيتار", "الكمان", "البيانو"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ماذا يُسمى الحدث الموسيقي الكبير الذي يجمع عدة فنانين؟", options: ["مهرجان أو حفل موسيقي", "ندوة", "مؤتمر", "معرض"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي الآلة الإيقاعية الأساسية في الموسيقى العربية والشرقية؟", options: ["الطبلة (الدربكة)", "الطبل الغربي", "الدرامز", "الأجراس"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "arabic-music": [
    { questionText: "من هي الفنانة اللبنانية الملقبة بـ\"سفيرة الأغنية اللبنانية إلى النجوم\"؟", options: ["فيروز", "صباح", "وردة", "ماجدة الرومي"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو الملحن المصري الملقب بـ\"عبقري الموسيقى العربية\"؟", options: ["محمد عبد الوهاب", "بليغ حمدي", "سيد مكاوي", "زكريا أحمد"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هي المطربة الملقبة بـ\"كوكب الشرق\"؟", options: ["أم كلثوم", "أسمهان", "ليلى مراد", "نجاة الصغيرة"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الموسيقار اللبناني الراحل ابن السيدة فيروز؟", options: ["زياد الرحباني", "عاصي الرحباني", "منصور الرحباني", "إلياس الرحباني"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي دولة عربية يُنسب إليها فن \"الراي\" الموسيقي؟", options: ["الجزائر", "المغرب", "تونس", "ليبيا"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "fairuz": [
    { questionText: "ما هي جنسية الفنانة فيروز؟", options: ["لبنانية", "سورية", "مصرية", "أردنية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هما الأخوان الملحنان اللذان تعاونا مع فيروز في معظم أعمالها الكلاسيكية؟", options: ["الأخوان الرحباني", "الأخوان أبو خليل القباني", "الأخوان فليفل", "الأخوان شهاب"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو ابن فيروز الذي أصبح ملحنًا وموسيقيًا معروفًا بأسلوبه الخاص؟", options: ["زياد الرحباني", "هلي الرحباني", "ريما الرحباني", "بشير الرحباني"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من أي بلد انطلقت فيروز لتصبح من أشهر مطربات العالم العربي؟", options: ["لبنان", "مصر", "سوريا", "العراق"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "بأي نوع من الأغاني اشتهرت فيروز إلى جانب الأغاني العاطفية؟", options: ["الأغاني الوطنية والتراثية", "الراب", "الروك", "الأغاني الإلكترونية"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "umm-kulthum": [
    { questionText: "ما هو اللقب الشهير للمطربة أم كلثوم؟", options: ["كوكب الشرق", "سيدة الغناء", "ملكة الطرب", "أميرة الأغنية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي جنسية أم كلثوم؟", options: ["مصرية", "لبنانية", "سورية", "تونسية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "بماذا اشتهرت حفلات أم كلثوم من ناحية طول أداء الأغنية الواحدة؟", options: ["قد تتجاوز الساعة للأغنية الواحدة", "دقائق معدودة فقط", "نصف دقيقة", "لا تتجاوز 5 دقائق"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "في أي يوم من الشهر اشتهرت أم كلثوم بإحياء حفلاتها الإذاعية الشهيرة؟", options: ["أول خميس من كل شهر", "كل جمعة", "كل سبت", "نهاية كل شهر"], correctAnswerIndex: 0, difficulty: "hard" },
    { questionText: "من هم أبرز الملحنين الذين لحّنوا لأم كلثوم؟", options: ["محمد عبد الوهاب ورياض السنباطي", "فريد الأطرش فقط", "زكريا أحمد فقط", "عبد الحليم حافظ"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "global-pop": [
    { questionText: "من هي الفنانة الأمريكية الملقبة بـ\"ملكة البوب\"؟", options: ["مادونا", "بيونسيه", "ريحانا", "تايلور سويفت"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو الفنان الملقب بـ\"ملك البوب\"؟", options: ["مايكل جاكسون", "إلفيس بريسلي", "بروس سبرينغستين", "بول مكارتني"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي فرقة بريطانية ضمت جون لينون وبول مكارتني وتُعد من أنجح فرق البوب/الروك؟", options: ["البيتلز", "رولينغ ستونز", "كوين", "ABBA"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو مغني أغنية \"Shape of You\"؟", options: ["إد شيران", "جاستن بيبر", "بروس سبرينغستين", "تشارلي بوث"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي مغنية أمريكية اشتهرت بألبوم \"1989\" وأغانيها السيرة الذاتية؟", options: ["تايلور سويفت", "أريانا غراندي", "بيلي أيليش", "دوا ليبا"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "rock": [
    { questionText: "أي فرقة بريطانية اشتهرت بأغنية \"Bohemian Rhapsody\"؟", options: ["كوين", "البيتلز", "رولينغ ستونز", "ليد زيبلن"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو المغني الملقب بـ\"ملك الروك آند رول\"؟", options: ["إلفيس بريسلي", "مايكل جاكسون", "جيمس براون", "تشاك بيري"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو مغني وقائد فرقة \"Queen\" الراحل؟", options: ["فريدي ميركوري", "بريان ماي", "روجر تايلور", "جون ديكون"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي فرقة أمريكية قادها كورت كوبين واشتهرت بموسيقى الروك البديل في التسعينيات؟", options: ["نيرفانا", "بيرل جام", "فو فايترز", "ساوندغاردن"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي الآلة الأساسية إلى جانب الغيتار الكهربائي في موسيقى الروك؟", options: ["الطبول (الدرامز)", "البيانو الكلاسيكي", "العود", "الناي"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "history-general": [
    { questionText: "في أي عام بدأت الحرب العالمية الأولى؟", options: ["1914", "1916", "1918", "1939"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو القائد الفرنسي الذي هُزم في معركة واترلو؟", options: ["نابليون بونابرت", "لويس السادس عشر", "شارل ديغول", "لويس نابليون"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي حضارة قديمة بنت أهرامات الجيزة؟", options: ["المصريون القدماء", "الرومان", "الإغريق", "البابليون"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "في أي قرن سقطت الإمبراطورية الرومانية الغربية؟", options: ["القرن الخامس الميلادي", "القرن العاشر", "القرن الثالث", "القرن الأول"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو أول رئيس للولايات المتحدة الأمريكية؟", options: ["جورج واشنطن", "أبراهام لينكولن", "توماس جيفرسون", "بنجامين فرانكلين"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "arab-islamic-history": [
    { questionText: "في أي مدينة نزل الوحي على النبي محمد لأول مرة؟", options: ["مكة المكرمة", "المدينة المنورة", "القدس", "دمشق"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الخليفة الراشدي الأول بعد وفاة النبي محمد؟", options: ["أبو بكر الصديق", "عمر بن الخطاب", "عثمان بن عفان", "علي بن أبي طالب"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو القائد المسلم الذي استعاد القدس من الصليبيين عام 1187؟", options: ["صلاح الدين الأيوبي", "طارق بن زياد", "خالد بن الوليد", "هارون الرشيد"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي دولة إسلامية اتخذت من بغداد عاصمة لها في أوج ازدهارها العلمي؟", options: ["الدولة العباسية", "الدولة الأموية", "الدولة الفاطمية", "الدولة العثمانية"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو القائد المسلم الذي فتح الأندلس بعبوره من المغرب؟", options: ["طارق بن زياد", "صلاح الدين الأيوبي", "خالد بن الوليد", "عمرو بن العاص"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "ww2": [
    { questionText: "في أي عام انتهت الحرب العالمية الثانية؟", options: ["1943", "1945", "1947", "1950"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "من هو الزعيم النازي الذي قاد ألمانيا خلال الحرب العالمية الثانية؟", options: ["أدولف هتلر", "بينيتو موسوليني", "ونستون تشرشل", "فرانكلين روزفلت"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم إنزال الحلفاء الشهير على شواطئ نورماندي عام 1944؟", options: ["يوم النزول (D-Day)", "عملية بارباروسا", "معركة ستالينغراد", "معركة الأردين"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي مدينتين يابانيتين ألقيت عليهما القنابل الذرية عام 1945؟", options: ["هيروشيما وناغازاكي", "طوكيو وأوساكا", "كيوتو وناغويا", "يوكوهاما وكوبي"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو رئيس وزراء بريطانيا خلال معظم فترة الحرب العالمية الثانية؟", options: ["ونستون تشرشل", "نيفيل تشامبرلين", "كليمنت أتلي", "أنتوني إيدن"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "ancient-egypt": [
    { questionText: "ما اسم الكتابة الرمزية المصرية القديمة؟", options: ["الهيروغليفية", "المسمارية", "اللاتينية", "الفينيقية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو أشهر أثر مصري قديم يقع بجوار أهرامات الجيزة؟", options: ["أبو الهول", "معبد الكرنك", "وادي الملوك", "معبد أبو سمبل"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو الملك الفرعوني الشاب الذي اكتُشفت مقبرته كاملة عام 1922؟", options: ["توت عنخ آمون", "رمسيس الثاني", "خوفو", "أخناتون"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو النهر الذي قامت حوله الحضارة المصرية القديمة؟", options: ["نهر النيل", "نهر الفرات", "نهر دجلة", "نهر الأردن"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هي الملكة المصرية الشهيرة التي ارتبط اسمها بيوليوس قيصر ومارك أنطوني؟", options: ["كليوباترا", "نفرتيتي", "حتشبسوت", "نفرتاري"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "lebanon-history": [
    { questionText: "في أي عام أُعلن استقلال لبنان؟", options: ["1943", "1946", "1920", "1958"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي عاصمة لبنان؟", options: ["بيروت", "طرابلس", "صيدا", "زحلة"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي حضارة قديمة اشتهرت بالتجارة البحرية وانطلقت من سواحل لبنان الحالي؟", options: ["الفينيقيون", "الآشوريون", "الفرس", "الرومان"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم سلسلة الجبال الشهيرة التي تحمل اسم لبنان وتمتد على طول البلاد؟", options: ["جبل لبنان", "جبل الشيخ", "جبل صنين", "جبل عامل"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "في أي مدينة لبنانية تقع قلعة بعلبك الأثرية الرومانية؟", options: ["بعلبك", "بيروت", "جبيل", "صور"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "geography-general": [
    { questionText: "ما هي أكبر قارة في العالم من حيث المساحة؟", options: ["آسيا", "أفريقيا", "أمريكا الشمالية", "أوروبا"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو أطول نهر في العالم بحسب ما يُدرَّس تقليديًا؟", options: ["نهر النيل", "نهر الأمازون", "نهر المسيسيبي", "نهر اليانغتسي"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو أكبر محيطات العالم مساحة؟", options: ["المحيط الهادئ", "المحيط الأطلسي", "المحيط الهندي", "المحيط المتجمد الشمالي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي أعلى قمة جبلية في العالم؟", options: ["إفرست", "كيليمنجارو", "إلبروس", "ماونت بلانك"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي أكبر صحراء حارة في العالم؟", options: ["الصحراء الكبرى", "صحراء غوبي", "صحراء كالاهاري", "الربع الخالي"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "capitals-countries": [
    { questionText: "ما هي عاصمة فرنسا؟", options: ["باريس", "ليون", "مرسيليا", "نيس"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي عاصمة اليابان؟", options: ["طوكيو", "أوساكا", "كيوتو", "يوكوهاما"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي عاصمة إيطاليا؟", options: ["روما", "ميلانو", "نابولي", "تورينو"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي عاصمة كندا؟", options: ["أوتاوا", "تورونتو", "فانكوفر", "مونتريال"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي عاصمة أستراليا؟", options: ["كانبيرا", "سيدني", "ملبورن", "بيرث"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "arab-world-geography": [
    { questionText: "ما هي أكبر دولة عربية من حيث المساحة؟", options: ["الجزائر", "السعودية", "السودان", "مصر"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو النهر الذي يُعتبر شريان حياة مصر؟", options: ["النيل", "الفرات", "دجلة", "الأردن"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي دولة عربية تقع جغرافيًا بين قارتي آسيا وأفريقيا؟", options: ["مصر", "السعودية", "الأردن", "العراق"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي أطول سلسلة جبال في المغرب العربي؟", options: ["جبال الأطلس", "جبال الألب", "جبال الهيمالايا", "جبال الأنديز"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "أي دولة عربية تضم مدينة \"البتراء\" الأثرية؟", options: ["الأردن", "سوريا", "لبنان", "العراق"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "world-wonders": [
    { questionText: "أي عجائب الدنيا القديمة السبع لا يزال قائمًا حتى اليوم؟", options: ["أهرامات الجيزة", "حدائق بابل المعلقة", "تمثال زيوس", "منارة الإسكندرية"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "في أي دولة يقع تمثال المسيح الفادي؟", options: ["البرازيل", "الأرجنتين", "تشيلي", "المكسيك"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "في أي دولة تقع مدينة البتراء الأثرية؟", options: ["الأردن", "مصر", "سوريا", "العراق"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "في أي دولة يقع سور الصين العظيم؟", options: ["الصين", "اليابان", "منغوليا", "كوريا الجنوبية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "في أي مدينة هندية يقع \"تاج محل\"؟", options: ["أغرا", "دلهي", "مومباي", "بنغالور"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "science-general": [
    { questionText: "ما هو الغاز الذي يحتاجه الإنسان للتنفس؟", options: ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيدروجين"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي وحدة قياس القوة في الفيزياء؟", options: ["نيوتن", "واط", "جول", "باسكال"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم عدد الكواكب في المجموعة الشمسية بعد استبعاد بلوتو؟", options: ["7", "8", "9", "10"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "ما هو العنصر الكيميائي الذي رمزه \"O\"؟", options: ["الأكسجين", "الذهب", "الأوزون", "الأوكسيد"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو العالم المرتبط بنظرية الجاذبية بحسب قصة سقوط التفاحة الشهيرة؟", options: ["إسحاق نيوتن", "ألبرت أينشتاين", "غاليليو غاليلي", "نيكولا تسلا"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "space-astronomy": [
    { questionText: "ما هو الكوكب الأقرب إلى الشمس؟", options: ["عطارد", "الزهرة", "الأرض", "المريخ"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو أول إنسان مشى على سطح القمر؟", options: ["نيل أرمسترونغ", "يوري غاغارين", "باز ألدرين", "جون غلين"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم المجرة التي تنتمي إليها الأرض؟", options: ["درب التبانة", "أندروميدا", "العملاقة الحمراء", "الدب الأكبر"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو الكوكب الملقب بـ\"الكوكب الأحمر\"؟", options: ["المريخ", "الزهرة", "المشتري", "زحل"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي كوكب في المجموعة الشمسية يشتهر بحلقاته الواضحة؟", options: ["زحل", "المشتري", "أورانوس", "نبتون"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "tech-computers": [
    { questionText: "ماذا يعني اختصار \"WWW\" الذي نراه في روابط الإنترنت؟", options: ["الشبكة العنكبوتية العالمية", "جهاز حاسوب", "نوع ملف", "برنامج تصفح"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو المؤسس المشارك لشركة أبل؟", options: ["ستيف جوبز", "بيل غيتس", "إيلون ماسك", "مارك زوكربيرغ"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو نظام التشغيل الذي طورته شركة مايكروسوفت؟", options: ["ويندوز", "ماك أو إس", "لينكس", "أندرويد"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو مؤسس شركة مايكروسوفت؟", options: ["بيل غيتس", "ستيف جوبز", "لاري بيج", "جيف بيزوس"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الاسم الشائع لذاكرة الحاسوب المؤقتة سريعة الوصول؟", options: ["الرام (RAM)", "القرص الصلب", "المعالج", "كرت الشاشة"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "human-body": [
    { questionText: "كم عدد عظام جسم الإنسان البالغ تقريبًا؟", options: ["206", "150", "300", "100"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو أكبر عضو في جسم الإنسان؟", options: ["الجلد", "الكبد", "الدماغ", "الرئة"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم عدد غرف القلب البشري؟", options: ["4", "2", "3", "5"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو العضو المسؤول عن ضخ الدم في الجسم؟", options: ["القلب", "الكبد", "الكلى", "الرئة"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي الوظيفة الأساسية للرئتين في الجسم؟", options: ["التنفس وتبادل الغازات", "ضخ الدم", "الهضم", "التفكير"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "video-games-general": [
    { questionText: "ما اسم الشخصية الشهيرة التي تُعتبر رمز شركة نينتندو وتظهر في \"سوبر ماريو\"؟", options: ["ماريو", "سونيك", "لينك", "باك مان"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي الشركة المصنعة لجهاز \"بلايستيشن\"؟", options: ["سوني", "مايكروسوفت", "نينتندو", "سيغا"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي الشركة المصنعة لجهاز \"إكس بوكس\"؟", options: ["مايكروسوفت", "سوني", "نينتندو", "أبل"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي شركة تُصدر أشهر سلسلة ألعاب تحاكي كرة القدم؟", options: ["إي إيه سبورتس (EA Sports)", "أكتيفيجن", "يوبيسوفت", "روكستار"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو المصطلح الذي يُطلق على اللاعبين المحترفين في الألعاب التنافسية؟", options: ["الرياضات الإلكترونية (e-sports)", "الألعاب الجماعية", "الألعاب التعليمية", "الواقع الافتراضي"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "fifa": [
    { questionText: "أي شركة تُصدر سلسلة ألعاب فيفا لكرة القدم؟", options: ["إي إيه سبورتس (EA Sports)", "أكتيفيجن", "يوبيسوفت", "روكستار"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الاسم الجديد لسلسلة ألعاب فيفا بعد انتهاء الشراكة مع الاتحاد الدولي؟", options: ["EA Sports FC", "FIFA Ultimate", "Pro Evolution Soccer", "Football Manager"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو الوضع الشهير في اللعبة الذي يتيح بناء فريق أحلام من لاعبين حقيقيين؟", options: ["ألتيمت تيم (Ultimate Team)", "كاريير مود", "برو كلوبس", "كيك أوف"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي الرياضة التي تحاكيها سلسلة ألعاب فيفا؟", options: ["كرة القدم", "كرة السلة", "التنس", "الغولف"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "كم عدد اللاعبين الذين يمكن التحكم بفريقهم في مباراة عادية داخل اللعبة؟", options: ["11 لاعبًا", "5 لاعبين", "7 لاعبين", "9 لاعبين"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "fortnite": [
    { questionText: "ما هي الشركة المطورة للعبة فورتنايت؟", options: ["إيبك غيمز (Epic Games)", "أكتيفيجن", "EA", "يوبيسوفت"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو نمط اللعب الأشهر في فورتنايت الذي يتنافس فيه 100 لاعب للبقاء الأخير؟", options: ["باتل رويال", "كاريير مود", "تيم ديث ماتش", "كامبين"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ماذا يحدث للمنطقة الآمنة تدريجيًا خلال مباراة فورتنايت؟", options: ["تتقلص باستمرار (العاصفة)", "تتوسع", "تختفي فجأة", "لا تتغير"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي إحدى الآليات الأساسية المميزة للعبة فورتنايت مقارنة بألعاب باتل رويال الأخرى؟", options: ["جمع الموارد والبناء (Building)", "السحر", "الطيران الحر", "القفز المزدوج فقط"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "على أي أجهزة يمكن لعب فورتنايت؟", options: ["أجهزة متعددة (حاسوب، كونسول، هاتف)", "الحاسوب فقط", "الهاتف فقط", "أجهزة أركيد فقط"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "minecraft": [
    { questionText: "ما هو الطابع البصري المميز للعبة ماين كرافت؟", options: ["الأشكال المكعبة", "الرسوم الواقعية", "الرسوم المسطحة ثنائية الأبعاد", "الرسوم اليدوية"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هي الشركة التي طورت ماين كرافت قبل استحواذ مايكروسوفت عليها؟", options: ["موجانغ (Mojang)", "إيبك غيمز", "فالف", "نينتندو"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو النشاط الأساسي في لعبة ماين كرافت؟", options: ["البناء والتعدين والاستكشاف", "السباق بالسيارات", "كرة القدم", "حل الألغاز فقط"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي مادة نادرة توجد عميقًا تحت الأرض وتُستخدم لصناعة أدوات متقدمة؟", options: ["الماس", "الرمل", "العشب", "الخشب"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما اسم الكائن العدائي الذي ينفجر عند اقترابه من اللاعب في ماين كرافت؟", options: ["كريبر (Creeper)", "زومبي", "إندرمان", "سكيلتون"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "league-of-legends": [
    { questionText: "من هي الشركة المطورة للعبة League of Legends؟", options: ["رايوت غيمز (Riot Games)", "فالف", "بليزارد", "إيبك غيمز"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو تصنيف نوع اللعبة الذي تنتمي إليه League of Legends؟", options: ["ساحة معارك متعددة اللاعبين (MOBA)", "باتل رويال", "لعبة رياضية", "لعبة سباق"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو الاسم الذي يُطلق على الشخصيات التي يتحكم بها اللاعبون في اللعبة؟", options: ["الأبطال (Champions)", "الوحوش", "الجنود", "الحراس"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم عدد اللاعبين المعتاد في الفريق الواحد بمباراة تقليدية؟", options: ["5 لاعبين", "3 لاعبين", "7 لاعبين", "10 لاعبين"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو اسم البطولة العالمية السنوية الكبرى للعبة؟", options: ["بطولة العالم (Worlds)", "الأولمبياد الإلكتروني", "كأس العالم", "ماستر كب"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "general-knowledge": [
    { questionText: "كم عدد أيام السنة الكبيسة؟", options: ["366 يومًا", "365 يومًا", "360 يومًا", "370 يومًا"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي اللغة الأكثر تحدثًا في العالم كلغة أم؟", options: ["الصينية الماندرين", "الإنجليزية", "الإسبانية", "العربية"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "كم عدد قارات العالم؟", options: ["7", "5", "6", "8"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو أسرع حيوان بري في العالم؟", options: ["الفهد الصياد (الشيتا)", "الأسد", "الحصان", "النمر"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو أكبر محيط في العالم من حيث المساحة؟", options: ["المحيط الهادئ", "المحيط الأطلسي", "المحيط الهندي", "المحيط المتجمد الشمالي"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "world-literature": [
    { questionText: "من هو مؤلف رواية \"الحرب والسلام\"؟", options: ["ليو تولستوي", "فيودور دوستويفسكي", "أنطون تشيخوف", "ماكسيم غوركي"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو الكاتب المسرحي الإنجليزي صاحب \"هاملت\" و\"روميو وجولييت\"؟", options: ["ويليام شكسبير", "تشارلز ديكنز", "أوسكار وايلد", "جورج أورويل"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "من هو مؤلف سلسلة روايات \"سيد الخواتم\"؟", options: ["ج.ر.ر. تولكين", "ج.ك. رولينغ", "س.س. لويس", "جورج مارتن"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو الكاتب الروسي صاحب رواية \"الجريمة والعقاب\"؟", options: ["فيودور دوستويفسكي", "ليو تولستوي", "أنطون تشيخوف", "بوريس باسترناك"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو مؤلف رواية \"مئة عام من العزلة\"؟", options: ["غابرييل غارسيا ماركيز", "بابلو نيرودا", "خورخي بورخيس", "ماريو بارغاس يوسا"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "arabic-literature": [
    { questionText: "من هو الشاعر العباسي الملقب بـ\"شاعر الحكمة\" واشتهر بالفخر؟", options: ["أبو الطيب المتنبي", "أبو نواس", "البحتري", "أبو تمام"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو الأديب المصري الحائز على جائزة نوبل للآداب؟", options: ["نجيب محفوظ", "طه حسين", "توفيق الحكيم", "عباس محمود العقاد"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ماذا تعني \"المعلقات\" في الشعر الجاهلي؟", options: ["قصائد كانت تُعلّق على الكعبة لجودتها", "كتب دينية", "قصص شعبية", "كتب طبية"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "من هو مؤلف رواية \"مدن الملح\"؟", options: ["عبد الرحمن منيف", "نجيب محفوظ", "حنا مينة", "غسان كنفاني"], correctAnswerIndex: 0, difficulty: "hard" },
    { questionText: "أي شاعر عربي يُلقب بـ\"شاعر القطرين\" (مصر ولبنان)؟", options: ["خليل مطران", "أحمد شوقي", "حافظ إبراهيم", "إيليا أبو ماضي"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "proverbs-sayings": [
    { questionText: "ما معنى المثل الشعبي \"الصبر مفتاح الفرج\"؟", options: ["الصبر يؤدي إلى حل المشاكل والراحة", "الفرج يأتي بالغضب", "يجب الاستعجال دائمًا", "الصبر بلا فائدة"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ماذا يعني المثل \"يد واحدة لا تصفق\"؟", options: ["التعاون ضروري لتحقيق النتائج", "العمل الفردي أفضل", "الصفق غير مهم", "لا علاقة للمثل بالتعاون"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما معنى المثل \"كل ممنوع مرغوب\"؟", options: ["الأشياء الممنوعة تثير الرغبة والفضول أكثر", "الممنوع غير مرغوب أبدًا", "لا علاقة بين المنع والرغبة", "المرغوب دائمًا مسموح"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ماذا يعني المثل \"العين بصيرة واليد قصيرة\"؟", options: ["رؤية الشيء دون القدرة على الحصول عليه", "اليد أقوى من العين", "البصر لا يفيد", "القصر صفة جسدية فقط"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما معنى المثل \"في التأني السلامة وفي العجلة الندامة\"؟", options: ["التمهل يجنب الأخطاء والاستعجال يسبب الندم", "السرعة دائمًا أفضل", "لا علاقة بين التأني والسلامة", "التأني يعني التوقف الكامل"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "food-general": [
    { questionText: "ما هو المكون الأساسي في صناعة الخبز؟", options: ["الدقيق (الطحين)", "السكر", "الزيت", "الملح فقط"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي دولة تشتهر عالميًا بأطباق البيتزا والباستا؟", options: ["إيطاليا", "فرنسا", "إسبانيا", "اليونان"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو المشروب الذي يُصنع من حبوب البن المحمصة؟", options: ["القهوة", "الشاي", "العصير", "الحليب"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي دولة تشتهر بأكلة السوشي؟", options: ["اليابان", "الصين", "كوريا الجنوبية", "تايلاند"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الخضار الأساسي المستخدم في صناعة الكاتشب؟", options: ["الطماطم (البندورة)", "البطاطا", "الجزر", "الخيار"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "arabic-cuisine": [
    { questionText: "ما هو الطبق الشعبي المكوّن أساسًا من الحمص المهروس والطحينة؟", options: ["الحمص (المسبحة)", "التبولة", "الفتوش", "المتبل"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "أي دولة عربية تشتهر بشكل خاص بأكلة الكبسة؟", options: ["السعودية", "لبنان", "المغرب", "مصر"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هي التبولة الشامية من حيث نوعها؟", options: ["سلطة باردة", "طبق حلويات", "نوع خبز", "مشروب"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الطبق المصري الشعبي المصنوع أساسًا من الفول المطبوخ؟", options: ["الفول المدمس", "الكشري", "الملوخية", "المحشي"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هي الحلوى الشرقية المصنوعة من عجين رقيق محشو بالجوز أو الفستق ومغطاة بالقطر؟", options: ["البقلاوة", "الكنافة", "المهلبية", "القطايف"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "riddles": [
    { questionText: "ما هو الشيء الذي كلما أخذت منه كبر؟", options: ["الحفرة", "الجبل", "البحر", "الكتاب"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "شيء له أسنان ولا يعض، فما هو؟", options: ["المشط", "السكين", "التمساح", "المنشار"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو الشيء الذي له عين واحدة ولا يرى؟", options: ["الإبرة", "المرآة", "الكاميرا", "النجمة"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما هو الشيء الذي كلما زاد نقص وزنه؟", options: ["الشمعة المحترقة", "الحجر", "الحديد", "الماء"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "ما اسم الشكل الهندسي الذي له ثلاثة أضلاع؟", options: ["المثلث", "المربع", "الدائرة", "المستطيل"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "quick-math": [
    { questionText: "ناتج جمع 7 + 8 يساوي؟", options: ["15", "14", "16", "17"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ناتج ضرب 6 × 7 يساوي؟", options: ["42", "36", "48", "49"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ما هو نصف العدد 100؟", options: ["50", "25", "75", "40"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "ناتج طرح 20 - 13 يساوي؟", options: ["7", "6", "8", "9"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "كم عدد أضلاع المربع؟", options: ["4", "3", "5", "6"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
};
