import { PregeneratedQuestion } from "./pregeneratedQuestions";

/**
 * English-language counterpart to `pregeneratedQuestions.ts` — a starter
 * pool of 5 hand-written English questions (by Claude, directly in
 * conversation, no API call) for every one of the 57 categories in
 * `categoryTaxonomy.ts`. These are independently written trivia, not literal
 * translations of the Arabic pool, so the two pools don't read like mirrors
 * of each other.
 *
 * `seedPregeneratedQuestions.ts` uploads these with `language: "en"`
 * explicitly, regardless of `CategorySeed.language` (which is `"ar"` for
 * every category right now) — so a category ends up with both an Arabic and
 * an English pool, and `pickNextQuestion` (see
 * `functions/src/scoring/resolveDuel.ts`) picks from whichever pool matches
 * the duel's `language`.
 *
 * Same as the Arabic pool: a STARTER, not the final word. Top it up the same
 * way — more hand-written entries here, or `generateQuestionsCore` with
 * `language: "en"` via the Claude API.
 *
 * Keys must match `CategorySeed.id` values in `categoryTaxonomy.ts` exactly.
 */
export const PREGENERATED_QUESTIONS_EN: Record<string, PregeneratedQuestion[]> = {
  "sports-general": [
    { questionText: "How many players from each team are on the court at once in basketball?", options: ["4", "5", "6", "7"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "In which year were the first modern Olympic Games held?", options: ["1896", "1900", "1904", "1912"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "How many periods are there in an NBA basketball game?", options: ["2", "3", "4", "5"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Which country hosted the 2022 FIFA World Cup?", options: ["Qatar", "Brazil", "Russia", "Germany"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What is the official distance of a marathon race?", options: ["42.195 km", "40 km", "50 km", "35 km"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "football-general": [
    { questionText: "How many players are on a football (soccer) team on the pitch at once?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "How many minutes is a standard football half?", options: ["30", "40", "45", "50"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Who holds the record for the most Ballon d'Or awards?", options: ["Lionel Messi", "Cristiano Ronaldo", "Pelé", "Diego Maradona"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "Which country has won the most FIFA World Cup titles?", options: ["Brazil", "Germany", "Italy", "Argentina"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "Which color card results in a player being sent off?", options: ["Yellow", "Red", "Green", "Blue"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "real-madrid": [
    { questionText: "In which city is Real Madrid based?", options: ["Barcelona", "Seville", "Madrid", "Bilbao"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is Real Madrid's home stadium called?", options: ["Camp Nou", "Santiago Bernabéu", "Wanda Metropolitano", "San Mamés"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What color is Real Madrid's traditional home kit?", options: ["Red", "Blue", "White", "Yellow"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "As of 2024, how many UEFA Champions League titles has Real Madrid won?", options: ["13", "14", "15", "16"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "In what year was Real Madrid founded?", options: ["1899", "1902", "1910", "1920"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "barcelona": [
    { questionText: "In which city is FC Barcelona based?", options: ["Madrid", "Barcelona", "Valencia", "Bilbao"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is FC Barcelona's home stadium called?", options: ["Santiago Bernabéu", "Camp Nou", "Metropolitano", "Mestalla"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "FC Barcelona's motto \"Més que un club\" translates to what in English?", options: ["More than a club", "One team, one city", "Forever blue and red", "Champions forever"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "What is FC Barcelona's famous youth academy called?", options: ["La Fábrica", "La Masia", "La Cantera", "El Vivero"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "In what year was FC Barcelona founded?", options: ["1899", "1902", "1905", "1910"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "man-utd": [
    { questionText: "In which city is Manchester United based?", options: ["Liverpool", "Manchester", "London", "Leeds"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is Manchester United's home stadium called?", options: ["Anfield", "Old Trafford", "Etihad Stadium", "Elland Road"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What nickname is Manchester United known by?", options: ["The Gunners", "The Red Devils", "The Toffees", "The Reds"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which manager led Manchester United to a historic treble in 1999?", options: ["José Mourinho", "Sir Alex Ferguson", "David Moyes", "Louis van Gaal"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "In what year was Manchester United founded (as Newton Heath)?", options: ["1878", "1885", "1892", "1902"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "liverpool": [
    { questionText: "In which city is Liverpool FC based?", options: ["Manchester", "Liverpool", "Birmingham", "Leeds"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is Liverpool FC's home stadium called?", options: ["Anfield", "Goodison Park", "St James' Park", "Villa Park"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What is Liverpool FC's famous anthem?", options: ["Blue Moon", "You'll Never Walk Alone", "Glory Glory", "Fields of Anfield Road"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What nickname is Liverpool FC known by?", options: ["The Reds", "The Blues", "The Toffees", "The Hammers"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "In what year did Liverpool famously come back from 3-0 down to win the Champions League final against AC Milan?", options: ["2001", "2005", "2007", "2019"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "arab-national-teams": [
    { questionText: "Which Arab country reached the semi-finals of the 2022 FIFA World Cup?", options: ["Egypt", "Morocco", "Saudi Arabia", "Tunisia"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which Arab country has won the most Africa Cup of Nations titles?", options: ["Egypt", "Algeria", "Morocco", "Tunisia"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "What is the nickname of the Egyptian national football team?", options: ["The Eagles", "The Pharaohs", "The Lions", "The Falcons"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which Arab country hosted the 2022 FIFA World Cup?", options: ["UAE", "Qatar", "Saudi Arabia", "Bahrain"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the nickname of the Moroccan national football team?", options: ["The Atlas Lions", "The Desert Foxes", "The Eagles of Carthage", "The Pharaohs"], correctAnswerIndex: 0, difficulty: "medium" },
  ],
  "world-cup": [
    { questionText: "How often is the FIFA World Cup held?", options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Which country hosted the first FIFA World Cup in 1930?", options: ["Uruguay", "Brazil", "France", "Italy"], correctAnswerIndex: 0, difficulty: "hard" },
    { questionText: "Which country has won the most World Cup titles?", options: ["Germany", "Brazil", "Argentina", "Italy"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which country won the 2022 FIFA World Cup?", options: ["France", "Argentina", "Croatia", "Brazil"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the trophy given to the World Cup winner called?", options: ["The Jules Rimet Trophy", "The FIFA World Cup Trophy", "The Golden Cup", "The Champions Trophy"], correctAnswerIndex: 1, difficulty: "medium" },
  ],
  "basketball-nba": [
    { questionText: "How many players from each team are on the court at once in the NBA?", options: ["4", "5", "6", "7"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "How many quarters are in an NBA game?", options: ["2", "3", "4", "5"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Who became the NBA's all-time leading scorer in 2023?", options: ["Kobe Bryant", "LeBron James", "Kareem Abdul-Jabbar", "Michael Jordan"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which team has won the most NBA championships?", options: ["Los Angeles Lakers", "Chicago Bulls", "Boston Celtics", "Golden State Warriors"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "How many points is a shot from beyond the arc worth?", options: ["1", "2", "3", "4"], correctAnswerIndex: 2, difficulty: "easy" },
  ],
  "tennis": [
    { questionText: "How many Grand Slam tournaments are there each year?", options: ["2", "3", "4", "5"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is a score of zero called in tennis?", options: ["Zero", "Love", "Nil", "Duck"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which Grand Slam tournament is played on clay courts?", options: ["Wimbledon", "US Open", "Australian Open", "French Open"], correctAnswerIndex: 3, difficulty: "medium" },
    { questionText: "As of 2023, who holds the record for most men's Grand Slam singles titles?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Andy Murray"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the maximum number of sets played in a men's Grand Slam singles match?", options: ["3", "4", "5", "7"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "movies-general": [
    { questionText: "Which award is considered the highest honor in the film industry?", options: ["Golden Globe", "BAFTA", "Academy Award (Oscar)", "Cannes Palme d'Or"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Who directed both \"Titanic\" and \"Avatar\"?", options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Peter Jackson"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "As of 2023, what was the highest-grossing film of all time (unadjusted)?", options: ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars: The Force Awakens"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "In which country is Hollywood located?", options: ["United Kingdom", "Canada", "United States", "Australia"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Which film won the Academy Award for Best Picture for 1994?", options: ["Pulp Fiction", "The Shawshank Redemption", "Forrest Gump", "The Lion King"], correctAnswerIndex: 2, difficulty: "medium" },
  ],
  "marvel": [
    { questionText: "What is Iron Man's real name?", options: ["Steve Rogers", "Tony Stark", "Bruce Banner", "Peter Parker"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which team includes Iron Man, Captain America, and Thor?", options: ["The X-Men", "The Avengers", "The Fantastic Four", "The Guardians of the Galaxy"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What metal is Captain America's shield famously made of?", options: ["Adamantium", "Vibranium", "Titanium", "Uru"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Who is the main villain in \"Avengers: Infinity War\"?", options: ["Loki", "Ultron", "Thanos", "Red Skull"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is Spider-Man's real name?", options: ["Peter Parker", "Miles Morales", "Harry Osborn", "Eddie Brock"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "harry-potter": [
    { questionText: "What is the name of the school Harry Potter attends?", options: ["Beauxbatons", "Durmstrang", "Hogwarts", "Ilvermorny"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Which house is Harry Potter sorted into?", options: ["Slytherin", "Gryffindor", "Ravenclaw", "Hufflepuff"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Who is the main antagonist of the Harry Potter series?", options: ["Draco Malfoy", "Severus Snape", "Lord Voldemort", "Bellatrix Lestrange"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "Who wrote the Harry Potter book series?", options: ["J.K. Rowling", "J.R.R. Tolkien", "C.S. Lewis", "Suzanne Collins"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What is the name of Harry Potter's pet owl?", options: ["Errol", "Pigwidgeon", "Hedwig", "Fawkes"], correctAnswerIndex: 2, difficulty: "medium" },
  ],
  "star-wars": [
    { questionText: "Who is Luke Skywalker's father?", options: ["Obi-Wan Kenobi", "Emperor Palpatine", "Darth Vader", "Yoda"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What color is Yoda?", options: ["Blue", "Green", "Grey", "Brown"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the name of Han Solo's ship?", options: ["Star Destroyer", "X-Wing", "Millennium Falcon", "Slave I"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What order of warrior-monks do Luke Skywalker and Obi-Wan belong to?", options: ["The Sith", "The Jedi Order", "The Mandalorians", "The Rebel Alliance"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Who created the Star Wars franchise?", options: ["Steven Spielberg", "George Lucas", "James Cameron", "Ridley Scott"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "tv-shows-general": [
    { questionText: "Which streaming service produced the show \"Stranger Things\"?", options: ["Hulu", "Netflix", "Amazon Prime", "Disney+"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "\"The Simpsons\" is set in a fictional town called what?", options: ["Quahog", "South Park", "Springfield", "Pawnee"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What are the main characters' profession in \"Grey's Anatomy\"?", options: ["Lawyers", "Doctors", "Detectives", "Teachers"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "\"Breaking Bad\" is set in which U.S. state?", options: ["Arizona", "Texas", "New Mexico", "Nevada"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What genre is \"The Office\", a workplace mockumentary?", options: ["Drama", "Comedy", "Thriller", "Horror"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "friends": [
    { questionText: "How many main friends are there in the show \"Friends\"?", options: ["4", "5", "6", "7"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the name of the coffee shop where the friends hang out?", options: ["Central Perk", "The Grind", "Java Junction", "The Daily Grind"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What is Ross's profession?", options: ["Chef", "Paleontologist", "Actor", "Massage therapist"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Who is Chandler's roommate for most of the series?", options: ["Ross", "Joey", "Mike", "Gunther"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "In which city is \"Friends\" set?", options: ["Chicago", "Boston", "New York City", "Los Angeles"], correctAnswerIndex: 2, difficulty: "easy" },
  ],
  "got": [
    { questionText: "\"Game of Thrones\" is based on a book series by which author?", options: ["J.R.R. Tolkien", "George R.R. Martin", "Robert Jordan", "Brandon Sanderson"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the name of the fictional continent where most of the story is set?", options: ["Essos", "Westeros", "Middle-earth", "Narnia"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which house's sigil is a direwolf?", options: ["House Lannister", "House Targaryen", "House Stark", "House Baratheon"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the name of one of Daenerys Targaryen's dragons?", options: ["Smaug", "Drogon", "Falkor", "Toothless"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the massive ice structure that protects the Seven Kingdoms from the north?", options: ["The Wall", "The Barrier", "The Gate", "The Rampart"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "anime-general": [
    { questionText: "What is the Japanese term for hand-drawn or computer animation, used worldwide?", options: ["Manga", "Anime", "Kawaii", "Otaku"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the source material for many anime series usually called?", options: ["Light novel", "Manga", "Doujinshi", "Manhwa"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which anime series revolves around a notebook that can kill anyone whose name is written in it?", options: ["Attack on Titan", "Death Note", "Bleach", "Fullmetal Alchemist"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which studio produced \"Spirited Away\"?", options: ["Toei Animation", "Studio Ghibli", "Madhouse", "Sunrise"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the main character in \"Dragon Ball\"?", options: ["Vegeta", "Goku", "Piccolo", "Gohan"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "one-piece": [
    { questionText: "What is Luffy's dream/goal in \"One Piece\"?", options: ["To become Hokage", "To find the legendary treasure One Piece", "To defeat all Titans", "To become a ninja master"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What ability did Luffy gain from eating a Devil Fruit?", options: ["Fire powers", "A rubber body", "Invisibility", "Super speed"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the name of Luffy's pirate crew?", options: ["Straw Hat Pirates", "Red Hair Pirates", "Whitebeard Pirates", "Heart Pirates"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "Who created the \"One Piece\" manga?", options: ["Masashi Kishimoto", "Eiichiro Oda", "Akira Toriyama", "Tite Kubo"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the legendary treasure the series is named after?", options: ["The Grand Treasure", "One Piece", "The King's Hoard", "The Void Century"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "naruto": [
    { questionText: "What is Naruto's dream/goal in the series?", options: ["To become Hokage", "To find One Piece", "To become a Pokémon master", "To defeat Aizen"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What creature is sealed inside Naruto?", options: ["A Dragon", "The Nine-Tailed Fox", "A Phoenix", "A Titan"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the name of Naruto's home village?", options: ["Sunagakure", "Kirigakure", "Konohagakure", "Iwagakure"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "Who created the \"Naruto\" manga?", options: ["Eiichiro Oda", "Masashi Kishimoto", "Akira Toriyama", "Hiromu Arakawa"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Who is Naruto's rival and best friend throughout the series?", options: ["Kakashi Hatake", "Sasuke Uchiha", "Shikamaru Nara", "Rock Lee"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "arabic-drama-general": [
    { questionText: "What language are Arabic drama series primarily performed in?", options: ["Turkish", "Arabic", "Persian", "French"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "During which Islamic calendar month are most major Arabic TV dramas traditionally premiered?", options: ["Rajab", "Shaban", "Ramadan", "Muharram"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the Arabic term for a television drama series?", options: ["Musalsal", "Aghani", "Riwaya", "Masrahiya"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "The Egyptian film industry has historically been nicknamed after which Western film hub?", options: ["Bollywood", "Hollywood", "Nollywood", "Cinecittà"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which country dominated Arabic-language film production for most of the 20th century?", options: ["Lebanon", "Syria", "Egypt", "Morocco"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "classic-egyptian-films": [
    { questionText: "What is the primary language of classic Egyptian cinema?", options: ["Modern Standard Arabic only", "Egyptian Arabic", "French", "Turkish"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which decades are often called the \"Golden Age\" of Egyptian cinema?", options: ["1900s-1920s", "1940s-1960s", "1980s-1990s", "2000s-2010s"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Legendary singer Umm Kulthum also starred in several classic Egyptian works of what kind?", options: ["Films", "Plays", "Radio dramas", "Operas"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "In which decade did Egyptian cinema begin producing sound films?", options: ["1920s", "1930s", "1950s", "1960s"], correctAnswerIndex: 1, difficulty: "hard" },
    { questionText: "In which country were most classic black-and-white Arabic films produced?", options: ["Lebanon", "Egypt", "Iraq", "Jordan"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "ramadan-series": [
    { questionText: "During which month are most Arabic TV drama premieres concentrated?", options: ["Ramadan", "Shawwal", "Dhu al-Hijjah", "Rabi al-Awwal"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What is the Arabic term for a TV drama series?", options: ["Riwaya", "Musalsal", "Hikaya", "Masrahiya"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Approximately how many episodes does a typical Ramadan series have, one per night?", options: ["10", "20", "30", "50"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "Ramadan series are traditionally aired at what time of day?", options: ["Early morning", "Midday", "Evening", "Just before dawn"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the meal that breaks the daily fast, after which many Ramadan series air?", options: ["Suhoor", "Iftar", "Eid feast", "Duha"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "arabic-comedy": [
    { questionText: "What is the general term for a performance meant to make audiences laugh?", options: ["Tragedy", "Comedy", "Drama", "Documentary"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which Egyptian actor is widely considered a pioneer of Arabic comedy cinema?", options: ["Ismail Yassine", "Omar Sharif", "Youssef Chahine", "Naguib Mahfouz"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "What is a common setting for many classic Arabic comedy films?", options: ["Outer space", "Everyday family life", "Medieval battles", "Courtroom trials"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Major Arabic comedy star Adel Imam is from which country?", options: ["Lebanon", "Syria", "Egypt", "Jordan"], correctAnswerIndex: 2, difficulty: "hard" },
    { questionText: "What is a \"dramedy\" a blend of?", options: ["Comedy and drama", "Horror and comedy", "Action and romance", "Musical and thriller"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "turkish-dubbed-drama": [
    { questionText: "Turkish dramas broadcast in Arabic are typically translated using which method?", options: ["Subtitles only", "Dubbing (voice-over)", "Live interpretation", "Silent intertitles"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Turkish dubbed dramas became especially popular across the Arab world starting in which decade?", options: ["1980s", "1990s", "2000s", "2020s"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What language are Turkish dramas originally produced in before being dubbed?", options: ["Arabic", "Turkish", "Persian", "Kurdish"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the general term for replacing a show's original dialogue with a new language track?", options: ["Subtitling", "Dubbing", "Captioning", "Localization only"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which Turkish drama about Ottoman history became a huge hit across Arabic-speaking countries?", options: ["Resurrection: Ertugrul", "Magnificent Century", "Fatmagul", "Kara Sevda"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "music-general": [
    { questionText: "How many lines are in a standard musical staff?", options: ["4", "5", "6", "7"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What are the seven basic solfège notes in Western music?", options: ["A B C D E F G", "Do Re Mi Fa Sol La Ti", "One Two Three Four Five Six Seven", "Alpha Beta Gamma Delta Epsilon Zeta Eta"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the term for the speed at which a piece of music is played?", options: ["Pitch", "Tempo", "Timbre", "Dynamics"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which instrument typically has 88 keys?", options: ["Organ", "Piano", "Accordion", "Harpsichord"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is a piece of music for a solo performer with orchestral accompaniment called?", options: ["Sonata", "Symphony", "Concerto", "Étude"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "arabic-music": [
    { questionText: "Which pear-shaped stringed instrument is central to Arabic music?", options: ["Qanun", "Oud", "Nay", "Rebab"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the name of the modal system used in traditional Arabic music?", options: ["Raga", "Maqam", "Solfège", "Chord progression"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which Lebanese singer became an icon of Arabic music with songs like \"Kalimat\"?", options: ["Fairuz", "Umm Kulthum", "Sabah", "Warda"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "Which Egyptian singer was famously nicknamed \"Kawkab al-Sharq\", or \"Star of the East\"?", options: ["Fairuz", "Umm Kulthum", "Asmahan", "Layla Murad"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the traditional Arabic hand drum?", options: ["Darbuka", "Djembe", "Bongo", "Tabor"], correctAnswerIndex: 0, difficulty: "hard" },
  ],
  "fairuz": [
    { questionText: "What is Fairuz's nationality?", options: ["Egyptian", "Lebanese", "Syrian", "Jordanian"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which family of composers did Fairuz famously collaborate with for most of her career?", options: ["The Abdel Wahab Brothers", "The Rahbani Brothers", "The Assaf Brothers", "The Fayrouz Brothers"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Fairuz is considered one of the most famous singers in which region?", options: ["East Asia", "The Arab world", "South America", "Scandinavia"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which of these is one of Fairuz's most famous songs?", options: ["Kalimat", "Ya Msafer", "Enta Omri", "Alf Leila wa Leila"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "In which decade did Fairuz begin her singing career?", options: ["1940s", "1950s", "1970s", "1980s"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "umm-kulthum": [
    { questionText: "What is Umm Kulthum's nationality?", options: ["Lebanese", "Egyptian", "Iraqi", "Tunisian"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What nickname, meaning \"Star of the East\", was Umm Kulthum given?", options: ["Kawkab al-Sharq", "Sitt al-Kull", "Ward al-Sharq", "Malikat al-Ghina"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "Umm Kulthum's famous monthly concerts were traditionally broadcast on which day of the week?", options: ["Monday", "Thursday", "Friday", "Sunday"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "In which decade did Umm Kulthum pass away?", options: ["1960s", "1970s", "1980s", "1990s"], correctAnswerIndex: 1, difficulty: "hard" },
    { questionText: "Umm Kulthum is considered one of the greatest singers in the history of what kind of music?", options: ["Arabic music", "Classical European music", "Jazz", "Flamenco"], correctAnswerIndex: 0, difficulty: "easy" },
  ],
  "global-pop": [
    { questionText: "Who is known as the \"King of Pop\"?", options: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Who is known as the \"Queen of Pop\"?", options: ["Madonna", "Britney Spears", "Beyoncé", "Cher"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "Which pop star released the album \"1989\"?", options: ["Ariana Grande", "Taylor Swift", "Katy Perry", "Lady Gaga"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which Swedish pop group is known for hits like \"Dancing Queen\"?", options: ["Roxette", "Ace of Base", "ABBA", "a-ha"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is Michael Jackson's best-selling album of all time called?", options: ["Bad", "Off the Wall", "Thriller", "Dangerous"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "rock": [
    { questionText: "Which British band recorded the album \"Abbey Road\"?", options: ["The Rolling Stones", "The Beatles", "Led Zeppelin", "Pink Floyd"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Who is known as the \"King of Rock and Roll\"?", options: ["Chuck Berry", "Elvis Presley", "Little Richard", "Buddy Holly"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Freddie Mercury was the lead singer of which rock band?", options: ["Queen", "The Who", "Genesis", "Deep Purple"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "Which American rock band released the album \"Nevermind\" in 1991?", options: ["Pearl Jam", "Soundgarden", "Nirvana", "Alice in Chains"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "Which iconic guitarist is known for songs like \"Purple Haze\"?", options: ["Eric Clapton", "Jimmy Page", "Jimi Hendrix", "Slash"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "history-general": [
    { questionText: "In which year did World War II end?", options: ["1943", "1944", "1945", "1946"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Who was the first President of the United States?", options: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "In which year did the French Revolution begin?", options: ["1776", "1789", "1804", "1815"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which ancient civilization built the pyramids of Giza?", options: ["The Romans", "The Ancient Egyptians", "The Greeks", "The Mesopotamians"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "In which year did the Berlin Wall fall?", options: ["1985", "1989", "1991", "1993"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "arab-islamic-history": [
    { questionText: "In which city was the Prophet Muhammad born?", options: ["Medina", "Mecca", "Jerusalem", "Damascus"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the name of the lunar-based Islamic calendar?", options: ["Gregorian calendar", "Hijri calendar", "Julian calendar", "Solar Hijri calendar"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which Islamic caliphate had its capital in Damascus?", options: ["Abbasid Caliphate", "Umayyad Caliphate", "Fatimid Caliphate", "Ottoman Caliphate"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which Abbasid caliph is famously associated with founding the House of Wisdom in Baghdad?", options: ["Harun al-Rashid", "Al-Ma'mun", "Al-Mansur", "Al-Mu'tasim"], correctAnswerIndex: 1, difficulty: "hard" },
    { questionText: "In which year (CE) did the Hijra, the migration from Mecca to Medina, take place?", options: ["610", "622", "632", "661"], correctAnswerIndex: 1, difficulty: "medium" },
  ],
  "ww2": [
    { questionText: "In which year did World War II begin?", options: ["1937", "1939", "1941", "1943"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which two countries were the primary Axis powers alongside Japan?", options: ["Germany and Italy", "France and Spain", "USSR and Poland", "Austria and Hungary"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What was the code name for the Allied invasion of Normandy in 1944?", options: ["Operation Torch", "D-Day (Operation Overlord)", "Operation Market Garden", "Operation Barbarossa"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which two Japanese cities had atomic bombs dropped on them in 1945?", options: ["Tokyo and Osaka", "Hiroshima and Nagasaki", "Kyoto and Kobe", "Yokohama and Sapporo"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "In which year did World War II end?", options: ["1944", "1945", "1946", "1947"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "ancient-egypt": [
    { questionText: "What are the massive stone tombs built for ancient Egyptian pharaohs called?", options: ["Ziggurats", "Pyramids", "Obelisks", "Mausoleums"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the ancient Egyptian picture-based writing system called?", options: ["Cuneiform", "Hieroglyphics", "Calligraphy", "Runes"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which river was central to ancient Egyptian civilization?", options: ["The Tigris", "The Euphrates", "The Nile", "The Jordan"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Which young pharaoh's nearly intact tomb was famously discovered in 1922?", options: ["Ramesses II", "Tutankhamun", "Akhenaten", "Khufu"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the process ancient Egyptians used to preserve bodies called?", options: ["Embalming only", "Mummification", "Cremation", "Petrification"], correctAnswerIndex: 1, difficulty: "medium" },
  ],
  "lebanon-history": [
    { questionText: "What is the capital of Lebanon?", options: ["Tripoli", "Beirut", "Sidon", "Byblos"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "In which year did Lebanon gain independence from France?", options: ["1936", "1943", "1948", "1958"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Lebanon's famous cedar trees appear on which national symbol?", options: ["Its currency only", "Its national flag", "Its passport cover only", "Its national anthem's title"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which ancient Phoenician city, located in modern Lebanon, was a major maritime trading power?", options: ["Byblos", "Carthage", "Alexandria", "Petra"], correctAnswerIndex: 0, difficulty: "hard" },
    { questionText: "Lebanon sits on the coast of which sea?", options: ["The Red Sea", "The Mediterranean Sea", "The Caspian Sea", "The Persian Gulf"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "geography-general": [
    { questionText: "What is the largest continent by area?", options: ["Africa", "Asia", "North America", "Europe"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the longest river in the world?", options: ["The Amazon", "The Nile", "The Yangtze", "The Mississippi"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the largest hot desert in the world?", options: ["The Gobi Desert", "The Sahara", "The Kalahari", "The Arabian Desert"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the tallest mountain in the world?", options: ["K2", "Mount Kilimanjaro", "Mount Everest", "Denali"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the smallest country in the world by area?", options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "capitals-countries": [
    { questionText: "What is the capital of France?", options: ["Lyon", "Paris", "Marseille", "Nice"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the capital of Japan?", options: ["Osaka", "Kyoto", "Tokyo", "Yokohama"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the capital of Kazakhstan?", options: ["Almaty", "Astana", "Shymkent", "Bishkek"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "arab-world-geography": [
    { questionText: "What is the largest country in the Arab world by area?", options: ["Saudi Arabia", "Algeria", "Egypt", "Sudan"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the capital of Egypt?", options: ["Alexandria", "Giza", "Cairo", "Luxor"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the capital of Saudi Arabia?", options: ["Jeddah", "Mecca", "Riyadh", "Medina"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the capital of Morocco?", options: ["Casablanca", "Marrakesh", "Fez", "Rabat"], correctAnswerIndex: 3, difficulty: "medium" },
    { questionText: "Which two seas does the Suez Canal connect?", options: ["The Red Sea and the Arabian Sea", "The Mediterranean Sea and the Red Sea", "The Black Sea and the Mediterranean Sea", "The Persian Gulf and the Red Sea"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "world-wonders": [
    { questionText: "Which of the Seven Wonders of the Ancient World still stands today?", options: ["The Hanging Gardens of Babylon", "The Great Pyramid of Giza", "The Colossus of Rhodes", "The Statue of Zeus"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "In which country is the Great Wall located?", options: ["Japan", "China", "Mongolia", "South Korea"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "In which country is the ancient city of Petra located?", options: ["Egypt", "Syria", "Jordan", "Israel"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "In which country is the statue of Christ the Redeemer located?", options: ["Argentina", "Brazil", "Peru", "Chile"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "The ancient Lighthouse of Alexandria, one of the Seven Wonders, was located in which country?", options: ["Greece", "Turkey", "Egypt", "Lebanon"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "science-general": [
    { questionText: "What is the chemical symbol for water?", options: ["HO", "H2O", "OH2", "H2O2"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What force pulls objects toward the Earth?", options: ["Magnetism", "Friction", "Gravity", "Inertia"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the \"powerhouse of the cell\" commonly called?", options: ["The nucleus", "The mitochondria", "The ribosome", "The cell membrane"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the chemical symbol for gold?", options: ["Ag", "Gd", "Au", "Go"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "space-astronomy": [
    { questionText: "What is the closest star to Earth?", options: ["Proxima Centauri", "The Sun", "Sirius", "Alpha Centauri"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the largest planet in our solar system?", options: ["Saturn", "Neptune", "Jupiter", "Uranus"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the name of our galaxy?", options: ["Andromeda", "The Milky Way", "Triangulum", "Whirlpool"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Who was the first human to walk on the Moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the name of NASA's rover that landed on Mars in 2021?", options: ["Curiosity", "Opportunity", "Perseverance", "Spirit"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "tech-computers": [
    { questionText: "What does \"CPU\" stand for?", options: ["Computer Processing Unit", "Central Processing Unit", "Central Program Utility", "Core Processing Unit"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Who co-founded Apple alongside Steve Wozniak?", options: ["Bill Gates", "Steve Jobs", "Larry Page", "Elon Musk"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What does \"WWW\" stand for?", options: ["World Web Wide", "World Wide Web", "Wide World Web", "Web World Wide"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which company developed the Windows operating system?", options: ["Apple", "Google", "Microsoft", "IBM"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "In what year was the first iPhone released?", options: ["2005", "2007", "2009", "2011"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "human-body": [
    { questionText: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the largest organ in the human body?", options: ["The liver", "The brain", "The skin", "The lungs"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Approximately how many bones are in the adult human body?", options: ["186", "206", "226", "246"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the largest internal organ in the human body?", options: ["The kidney", "The liver", "The stomach", "The pancreas"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the energy-producing organelle found inside cells called?", options: ["The nucleus", "The ribosome", "The mitochondria", "The Golgi apparatus"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "video-games-general": [
    { questionText: "Which company created the Mario franchise?", options: ["Sega", "Nintendo", "Sony", "Capcom"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What genre is the classic game \"Tetris\"?", options: ["Puzzle", "Platformer", "Racing", "Shooter"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "Which company developed the PlayStation console?", options: ["Microsoft", "Nintendo", "Sony", "Sega"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Which console is the best-selling video game console of all time?", options: ["Xbox 360", "Nintendo Wii", "PlayStation 2", "Game Boy"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "In what year was the arcade game \"Pong\" released?", options: ["1968", "1972", "1978", "1980"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "fifa": [
    { questionText: "What sport does the FIFA video game series simulate?", options: ["Basketball", "American Football", "Football (Soccer)", "Baseball"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "Which company publishes the FIFA / EA Sports FC video game series?", options: ["Activision", "EA Sports", "Take-Two", "Ubisoft"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the newer name for the FIFA video game series after 2023?", options: ["EA Sports FC", "Pro Football 24", "World Soccer League", "FIFA Ultimate"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "What is the popular mode where players build a squad of collected player cards?", options: ["Career Mode", "Ultimate Team", "Pro Clubs", "Volta"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "In what year was the first FIFA video game released?", options: ["1990", "1993", "1996", "1998"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "fortnite": [
    { questionText: "What is the main game mode where 100 players fight until one remains?", options: ["Team Deathmatch", "Battle Royale", "Capture the Flag", "Zombies mode"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which company developed Fortnite?", options: ["Epic Games", "Valve", "Ubisoft", "Activision"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What is the name of the in-game currency used to buy cosmetics in Fortnite?", options: ["Robux", "V-Bucks", "Credits", "Gold Bars"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which of these materials can players gather and use to build structures in Fortnite?", options: ["Wood, brick, and metal", "Only wood", "Only stone", "Gold and diamonds"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "In what year was Fortnite's Battle Royale mode released?", options: ["2015", "2017", "2019", "2021"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "minecraft": [
    { questionText: "What is the primary material players use to build things in Minecraft?", options: ["Bricks", "Blocks", "Tiles", "Panels"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which company owns Minecraft (via its studio Mojang)?", options: ["Sony", "Microsoft", "EA", "Tencent"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the hostile creature in Minecraft that explodes near players?", options: ["Zombie", "Skeleton", "Creeper", "Enderman"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the rarest, most valuable common ore players seek out in Minecraft?", options: ["Iron", "Gold", "Diamond", "Coal"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "In what year was Minecraft first released?", options: ["2009", "2011", "2013", "2015"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "league-of-legends": [
    { questionText: "What type of game is League of Legends?", options: ["First-person shooter", "MOBA (Multiplayer Online Battle Arena)", "Real-time strategy", "Racing game"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which company developed League of Legends?", options: ["Valve", "Riot Games", "Blizzard", "Epic Games"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What are the playable characters in League of Legends called?", options: ["Heroes", "Champions", "Agents", "Legends"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is League of Legends' biggest annual tournament called?", options: ["World Championship", "The International", "Major League Finals", "Champions Cup"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "In what year was League of Legends released?", options: ["2005", "2009", "2013", "2016"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "general-knowledge": [
    { questionText: "How many continents are there?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the largest ocean on Earth?", options: ["The Atlantic Ocean", "The Indian Ocean", "The Pacific Ocean", "The Arctic Ocean"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "How many colors are traditionally listed in a rainbow?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the official currency of Japan?", options: ["Won", "Yuan", "Yen", "Ringgit"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the smallest prime number?", options: ["0", "1", "2", "3"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "world-literature": [
    { questionText: "Who wrote \"Romeo and Juliet\"?", options: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Oscar Wilde"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Who wrote \"Pride and Prejudice\"?", options: ["Emily Brontë", "Jane Austen", "Virginia Woolf", "Mary Shelley"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Who wrote the dystopian novel \"1984\"?", options: ["Aldous Huxley", "Ray Bradbury", "George Orwell", "H.G. Wells"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "Which Russian author wrote \"War and Peace\"?", options: ["Fyodor Dostoevsky", "Anton Chekhov", "Leo Tolstoy", "Nikolai Gogol"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "Who wrote \"One Hundred Years of Solitude\"?", options: ["Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda", "Gabriel García Márquez"], correctAnswerIndex: 3, difficulty: "hard" },
  ],
  "arabic-literature": [
    { questionText: "What is considered the most famous collection of Arabic folk tales?", options: ["The Muqaddimah", "One Thousand and One Nights", "Kalila wa Dimna", "The Conference of the Birds"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Which pre-Islamic poet is considered one of the greatest classical Arabic poets, known for the Mu'allaqat?", options: ["Al-Mutanabbi", "Imru' al-Qais", "Abu Nuwas", "Al-Farazdaq"], correctAnswerIndex: 1, difficulty: "hard" },
    { questionText: "Which Egyptian author won the Nobel Prize in Literature in 1988?", options: ["Taha Hussein", "Naguib Mahfouz", "Tawfiq al-Hakim", "Yusuf Idris"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the classical Arabic poetic form built from paired rhyming lines?", options: ["Qasida", "Haiku", "Sonnet", "Ballad"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "What is the Arabic word for poetry?", options: ["Nathr", "Shi'r", "Khutba", "Riwaya"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "proverbs-sayings": [
    { questionText: "Proverbs are short traditional sayings that typically express what?", options: ["A joke", "A general truth or piece of advice", "A rhyme scheme", "A historical date"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "The Arabic proverb \"الصبر مفتاح الفرج\" is best translated into which English idea?", options: ["Silence is golden", "Patience is the key to relief", "Time heals all wounds", "Look before you leap"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which English proverb means you shouldn't judge someone or something by outward appearance alone?", options: ["Don't judge a book by its cover", "The early bird catches the worm", "Better late than never", "Practice makes perfect"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "What does the proverb \"A bird in the hand is worth two in the bush\" mean?", options: ["Birds are valuable pets", "Something you already have is better than a better thing you might get", "Two is always better than one", "Patience is required to catch birds"], correctAnswerIndex: 1, difficulty: "hard" },
    { questionText: "What word describes a short traditional saying that expresses a common truth?", options: ["Anecdote", "Proverb", "Metaphor", "Fable"], correctAnswerIndex: 1, difficulty: "easy" },
  ],
  "food-general": [
    { questionText: "What is the main ingredient in traditional pizza dough?", options: ["Rice flour", "Wheat flour", "Cornmeal", "Potato starch"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "Sushi is a traditional dish originating from which country?", options: ["China", "Thailand", "Japan", "Korea"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is the main grain used to make traditional couscous?", options: ["Rice", "Semolina wheat", "Barley", "Corn"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "Which spice, derived from the crocus flower, is the world's most expensive spice by weight?", options: ["Cinnamon", "Cardamom", "Saffron", "Vanilla"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What process turns grape juice into wine?", options: ["Distillation", "Pasteurization", "Fermentation", "Carbonation"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "arabic-cuisine": [
    { questionText: "What is hummus primarily made from?", options: ["Lentils", "Chickpeas", "Fava beans", "Eggplant"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What is the name of the popular skewered, grilled meat dish in Arabic cuisine?", options: ["Kebab", "Tagine", "Couscous", "Falafel"], correctAnswerIndex: 0, difficulty: "easy" },
    { questionText: "What are the two main ingredients in tabbouleh salad?", options: ["Rice and lamb", "Parsley and bulgur", "Yogurt and cucumber", "Eggplant and tahini"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the flaky, syrup-soaked pastry popular across the Arab world?", options: ["Kunafa", "Baklava", "Basbousa", "Maamoul"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What is the name of the traditional Levantine dish of layered eggplant, meat, and rice, served flipped upside down?", options: ["Mansaf", "Kabsa", "Maqluba", "Fattoush"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
  "riddles": [
    { questionText: "What has keys but can't open a single lock?", options: ["A map", "A piano", "A safe", "A diary"], correctAnswerIndex: 1, difficulty: "easy" },
    { questionText: "What has a face and two hands but no arms or legs?", options: ["A doll", "A statue", "A clock", "A mannequin"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What gets wetter the more it dries?", options: ["A sponge", "A towel", "A cloud", "Rain"], correctAnswerIndex: 1, difficulty: "medium" },
    { questionText: "What can travel around the world while staying in a single corner?", options: ["A stamp", "A coin", "A letter", "A shadow"], correctAnswerIndex: 0, difficulty: "medium" },
    { questionText: "The more you take of it, the more you leave behind. What is it?", options: ["Time", "Footsteps", "Memories", "Water"], correctAnswerIndex: 1, difficulty: "hard" },
  ],
  "quick-math": [
    { questionText: "What is 7 + 8?", options: ["13", "14", "15", "16"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is 9 × 6?", options: ["45", "48", "54", "56"], correctAnswerIndex: 2, difficulty: "easy" },
    { questionText: "What is 144 ÷ 12?", options: ["10", "11", "12", "14"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is 15% of 200?", options: ["20", "25", "30", "35"], correctAnswerIndex: 2, difficulty: "medium" },
    { questionText: "What is the square root of 169?", options: ["11", "12", "13", "14"], correctAnswerIndex: 2, difficulty: "hard" },
  ],
};
